language: node_js
node_js:
  - node
  - lts/*

before_install:
  - npm install -g grunt-cli
install:
  - npm install
before_script:
  - node --version
  - npm --version
  - grunt --version
script:
  - grunt
